### ISSUE TITLE
Time series server should be able to read parameters from both the url (query params) and post body (JSON properties). If the same parameter is found in both the url and the post body, the one in the post body always takes priority.

### ISSUE THREAD

**Issue by Zodiase** [openskope/timeseries-service#10]
The parameters should have names:

```
datasetId
variableName
boundaryGeometry
start
end
```

(The `start` and `end` are there for now until we can truly support dates)

For example:

```
POST
http://staging.openskope.org/timeseries-service/api/v1/values?datasetId=paleocar&variableName=ppt_annual&start=1&end=2000

{
    "boundaryGeometry": {},
}
```

would be effectively the same as:

```
POST
http://staging.openskope.org/timeseries-service/api/v1/values

{
    "datasetId": "paleocar",
    "variableName": "ppt_annual",
    "boundaryGeometry": {},
    "start": "1",
    "end": "2000"
}
```

Parameters could appear in both the url and the JSON body. If so, the value in the JSON body **always** takes priority.

**Comment by tmcphillips** [comment]
Is the boundaryGeometry the same as before?  E.g. for a single point:
```
boundaryGeometry: {
    type: 'Point',
    coordinates: [-123, 45]
}
```

**Comment by Zodiase** [comment]
The server should be aware of the data types when reading from either the url or the JSON body. The example above just shows what's equivalent. The client side should never be expected to send a number type value in the JSON body as a string. But the server should better double check within the reasonable range of acceptable values.

And yes the boundary schema is not changed.

**Comment by tmcphillips** [comment]
Processing of POST requests now take both the query line parameters and the JSON body into account, and the latter takes priority if there is a conflict.
