### ISSUE TITLE
Naming convention for GeoTIFF files based on dataset and variable names

### ISSUE THREAD

**Issue by tmcphillips** [openskope/timeseries-service#11]
Currently all GeoTIFF files that serve as backing for this service are named using the following template:
```
{TIMESERIES_SERVICE_DATA}/{datasetId}_{variableName}.tif
```
where TIMESERIES_SERVICE_DATA is configurable for the service as a whole.

We need to establish what dataset ID and variable name should be used for each file in general, and how to handle spaces in those names, (Replace each space with underscore?)

And does the path template itself need to be configurable so that, for example, datasetId can be  part of a directory name if needed?

**Comment by Zodiase** [comment]
@jterstriep

**Comment by Zodiase** [comment]
@tmcphillips There's a possibility that a TIF file could not be addressed by simply combining the dataset ID and the variable name. For example, multiple datasets could potentially contain the same variable, if we were to treat datasets as logical grouping and variables as the real data files, there would need an indirection in the middle. But @jterstriep would be better at explaining this.

**Comment by jterstriep** [comment]
I was going to bring this up tomorrow. The basic layout on disk would map well to  {TIMESERIES_SERVICE_DATA}/{datasetId}/{variableName}. This uses the filesystem as the basis of finding data files. One of the purposes of clowder was to be able to map between dataset and file to find a file path. But since we're not using clowder right now, the above approach would be ok.

BTW, I would like to drop the dependency on the .tif extension. The extension can be included in the variableName parameter. I tried to test timeseries_service on .nc4 files and it didn't work because it was hardcoded to .tif.

**Comment by tmcphillips** [comment]
I've made the path to data files a configurable URI template (now called TIMESERIES_DATA_PATH_TEMPLATE) that can be used to declare the directory layout and naming scheme for data files for each variable.   The two variables in the template, datasetId and variableName, can go anywhere in the template and be parts of directory names, the data
filename or both.  An example would be:
```
TIMESERIES_DATA_PATH_TEMPLATE = /timeseries/{datasetId}/{variableName}.tif
```
A variable can be used more than once in the template, so this works too:
```
TIMESERIES_DATA_PATH_TEMPLATE = /timeseries/{datasetId}/{datasetId}_{variableName}.tif
```

**Comment by tmcphillips** [comment]
You also can leave the file extension (e.g. `.tif`) out of the template and either include it in one of the variables (if the template ends in that variable) or let the service find the appropriate file by trying a configurable set of possible extensions, e.g.:
```
TIMESERIES_DATA_FILE_EXTENSIONS = .tif .nc .nc4
```
The above configuration will cause the service first to look for an exact template match (no added extension), and then expand the template with each extension appended in turn, and return data from the first matching data file it finds.
