### ISSUE TITLE
Timeservice should detect when NaN is used as the NODATA value

### ISSUE THREAD

**Issue by tmcphillips** [openskope/timeseries-service#18]
Currently when NaN values are detected in a timeseries generated by gdallocationinfo or zonalinfo.py, the service reports an error.  NaN is commonly used as the NODATA value for floating point data sets. The service should detect when this this is the case and interpret NaN values in the output of gdallocationinfo accordingly.

**Comment by jterstriep** [comment]
There are several potential changes here:
1. zonalinfo could be changed to emit "null" appropriately for nodata. 
2. zonalinfo could be enhanced to take a geojson point and entirely replace gdallocationinfo
3. zonalinfo could use isclose when masking nodata on floating datasets.
4. zonalinfo could be enhanced to provide json output with additional stats (both scalar and timeseries)

**Comment by tmcphillips** [comment]
For now the timeseries service itself detects the NODATA value defined in the metadata of a data file,  detects this value in the output of either gdallocationinfo (for points) or zonalinfo.py (for regions), and replaces them with nulls in the response to the timeseries request.
