### ISSUE TITLE
Add support for POST requests with JSON body.

### ISSUE THREAD

**Issue by tmcphillips** [openskope/timeseries-service#4]
Support for averaging a variable over a spatial region requires that the REST API allow definition of this region in the body of a POST request.  The request schema proposed in issue [skope-interface/#105](https://github.com/openskope/skope-interface/issues/105)  is:

POST
Content-Type: application/json; charset=utf-8

```
{
    datasetId: <string>,
    variableName: <string>,
    boundaryGeometry: {
        type: <string> ("Point" | "Polygon"),
        coordinates: <Array>
    },
    period: {
        gte: <Date>,
        lte: <Date>
    }
}
```

**Comment by tmcphillips** [comment]
The service now supports POST requests.  The schema is similar to one proposed above but currently accepts a range.start and range.end representing the range of bands (with indices starting at zero) in the GeoTIFF to extract values from. 

Example for which there is a working test:

```
{
    datasetId: '5x5x5',
    variableName: 'temp',
    boundaryGeometry: {
        type: 'Point',
        coordinates: [-123, 45]
    },
    range: {
        start: 0,
        end: 4
    }
}
```

The above returns an array of 5 values from GeoTIFF file `5x5x5_temp.tif` using a similar schema:

```
 {
    "datasetId": "5x5x5", 
    "variableName": "temp",
    "boundaryGeometry": {
        "coordinates": [-123, 45], 
        "type": "Point"
    }, 
    "range": {
        "end": 4, 
        "start": 0
    }, 
    "values": [100, 200, 300, 400, 500]
}
```

See [create_test_geotiff.py ](https://github.com/openskope/timeseries-service/blob/6839af14270a60bdb8ebe8e221ee4466bbe2b8b3/scripts/create_test_geotiff.py)for definition of the test image used above.

**Comment by Zodiase** [comment]
Looks amazing. How can I test this with my development setup?

**Comment by tmcphillips** [comment]
Cool.  I'll get a Docker image together so you can easily configure and run the service locally.

**Comment by jterstriep** [comment]
How does the datasetId and variableName work together to create a file path?

**Comment by tmcphillips** [comment]
I've described the file path template convention in a new issue #11.
