### ISSUE TITLE
Deploy timeseries-service to staging environment.

### ISSUE THREAD

**Issue by tmcphillips** [openskope/timeseries-service#7]
The timeseries service will become part of the deployed SKOPE application, and to enable development of the UI should be deployed as soon as possible to the staging environment.

**Comment by tmcphillips** [comment]
The four GeoTIFF files that were used to serve time series to the SKOPE I prototype are now on the staging server and named to be accessible via the new timeseries service:

```
ubuntu@newstage:~/timeseries-service$ ls -g /projects/skope/staging/timeseries/
total 35100160
-rw-r--r-- 1 skope 8985635721 Mar  6 23:15 paleocar_gdd_may_sept.tif
-rw-r--r-- 1 skope 8985635721 Mar  6 23:28 paleocar_ppt_annual.tif
-rw-r--r-- 1 skope 8985635721 Mar  6 23:37 paleocar_ppt_may_sept.tif
-rw-r--r-- 1 skope 8985635721 Mar  6 23:52 paleocar_ppt_water_year.tif
```
With the current naming convention the above files can be accessed by requesting the `paleocar` dataset and the `gdd_may_sept`, `ppt_annual`, `ppt_may_sept` or `ppt_water_year` variables.

**Comment by tmcphillips** [comment]
The `timeseries-service` repo is now cloned on the staging server, and the service can be run in background using `docker-compose` by executing the command below in the top directory of the cloned repo:

```
sudo docker-compose up -d
```

**Comment by tmcphillips** [comment]
The timeseries service currently is accessible on port 8001 from the staging server.   It is possible to experiment with the service manually using GET requests. For example, following the link below returns the values of the first five bands (years) of the paleocar_ppt_annual.ppt file:

http://staging.openskope.org:8001/timeseries-service/api/v1/values?dataset=paleocar&variable=ppt_annual&lat=36.668&lng=-110.127&start=0&end=4

Output:
```
{"datasetId":"paleocar","variableName":"ppt_annual","values":[288,313,326,339,312],"range":{"start":0,"end":4},"boundaryGeometry":{"coordinates":[-110.127,36.668],"type":"Point"}}
```

**Comment by Zodiase** [comment]
Is this considered resolved?
